### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by y-kiku1111** [y-kiku1111/chat-space#1]
#IPアドレス
18.182.244.52

**Comment by mo1015** [comment]
菊池さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○Editボタンが見本と異なる
○サイドバーのグループ同士の間隔が見本と異なる**
<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/80580933-4e592e80-8a47-11ea-9fc4-f8cf79caf8c6.png">
<img width="591" alt="contents上部見本" src="https://user-images.githubusercontent.com/62644781/80581003-6e88ed80-8a47-11ea-9a2b-e7e78c289e13.png">
<img width="591" alt="サイドバー見本" src="https://user-images.githubusercontent.com/62644781/80581035-7f396380-8a47-11ea-871e-37b33e2f6e9b.png">

**○投稿フォームが見本通り実装されていない**
<img width="1186" alt="スクリーンショット 2020-04-29 18 25 32" src="https://user-images.githubusercontent.com/62644781/80580809-1d78f980-8a47-11ea-9725-b3e24abc577c.png">
**↓見本**
<img width="1195" alt="スクリーンショット 2020-04-29 17 50 57" src="https://user-images.githubusercontent.com/62644781/80580818-236eda80-8a47-11ea-9d64-5e6c6224b273.png">
**↓参考カリキュラム**
<img width="691" alt="投稿フォーム見本" src="https://user-images.githubusercontent.com/62644781/80580835-28338e80-8a47-11ea-81b1-14dbe70f4d62.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by y-kiku1111** [comment]
ご確認ありがとうございます！
頂いた3点、修正いたしました！

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
